version: '3.3'

services:
  bot:
    container_name: bot
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /opt/services/bot/work-bot
    environment:
      - POSTGRES_DB=OSOR_DB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=238484
      - POSTGRES_HOST=localhost  # Используйте имя сервиса базы данных в качестве хоста
      - POSTGRES_PORT=5432
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: OSOR_DB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 238484
      POSTGRES_HOST: localhost
    expose:
      - "5432"
